---
title: Assessing the value of linking public health microbiology data to the UK Biobank
bibliography: references.bib
---

## Introduction
Infectious diseases have been one of the major causes of mortality worldwide, especially in children in developing countries. It is estimated that eight major infections (acquired immunodeficiency syndrome (AIDS), malaria, measles, hepatitis, dengue fever, rabies, tuberculosis and, yellow fever) caused more than 156 million deaths and put a burden of eight trillion dollars on the global economy in the year of 2016 (D. E. Bloom et al. 2020). The emergence of COVID-19 has further shed light on the importance and urgency of the study of infectious diseases comment::cite::. Infections are the results of complex interactions between hosts, pathogens, and environments. A major challenge of conducting comprehensive studies on infectious diseases is therefore considering the dynamics of all three factors. Another major challenge of studying infectious diseases in public health is the lack of statistical power as regions that have the infrastructure for comprehensive infection records collection are often also low in infectious disease prevalence comment::cite::. For example, only 4\% of human genome-wide association studies (GWAS) entries in the GWAS catalog (MacArthur et al., 2017) pertain to infectious diseases, contributing a mere 2.5\% to the total distinct variant-trait associations (Mozzi et al. 2018).
Here, we discuss (i) how UK biobank, a large scale prospective cohort study, offers opportunities to address these challenges. (ii) The current limitation of UK Biobank in identifying infection cases. (iii) how the integration to the recording of microbiological testing database in England has the potential to address these limitations.

### UK Biobank
UK Biobank is a large-scale prospective cohort study. It collects in-depth biomarkers, genetic and other health-related data from a cohort of around 500,000 participants who were between the age of 40 and 69 during recruitment in the UK. Since 2006, UK Biobank has been continuously updated with additions in health-related lifestyle data as well as blood, urine, and saliva samples. It serves as a crucial resource for studying health and diseases comment::cite::. The prospective nature of UK Biobank allows exposure assessment prior to disease onset, enhancing causal interpretations. It also allows infection cases to accumulate at scale overtime, which is particularly valuable in addressing the challenge of insufficient statistical power. Moreover, the comprehensive health-related data collection allows environmental and behavioral risk factors to be accounted for and investigated. Currently, the identification of infection events in UK Biobank is mainly through its integration of Hospital Episode Statistics (HES). HES includes detailed infection diagnostic records coded in International Classification of Diseases, Tenth Revision (ICD-10). Such infection records offer an opportunity for identifying infection cases for the study of infectious diseases. However, HES codings are based on clinical judgment, i.e. made on the basis of symptoms, signs and/or radiological investigations. Codings may be informed by the results of microbiological investigations, but are commonly made without them. Therefore, infectious disease syndromes (such as pneumonia, sepsis etc) may be due to multiple organisms that cannot be distinguished from the ICD-10 coding.

### Second Generation Surveillance Systems
The Second Generation Surveillance System (SGSS) is a national laboratory reporting system used by Public Health England (PHE; now UKHSA, the United Kingdom Health Security Agency) to capture routine laboratory data on infectious diseases and antimicrobial resistance in England. Since October 2010, diagnostic laboratories in England have been required to report microbiological test results involving human pathogens to PHE (UK Health Security Agency 2022). SGSS is the system/database through which the data of bacterial isolations and antimicrobial resistance from English laboratories are centralized, stored and managed by PHE. It contains detailed information on all positive microbiological isolates (microbial cultures) on which antimicrobial susceptibility testing is performed. Compared to infectious episodes recorded in HES, SGSS records provide a more granular and specific diagnosis of microbiologically-confirmed infection that includes both hospital patients and patients outside hospitals from whom general practitioners (family doctors) have taken specimens. SGSS provides information on specimen type (e.g. blood culture, urine sample), which is indicative of the likely infection site and severity, as blood culture positivity is a highly specific feature of severe infection (septicaemia). However, in contrast to UKB, SGSS lacks detailed information about the infected hosts.

